
# Simple Makefile for lldb tutorial code.
# -g flag enables lldb debugging.

lldb_tut: lldbtutorial.c
	clang -g -o lldb_tut lldbtutorial.c

hw5: hw5.c hw5_main.c hw5.h
	clang -Wall -g -o hw5 hw5.c hw5_main.c 