
int absVal(int);
int test_absVal(int);
int allOddBits();
int test_allOddBits();
int bang(int);
int test_bang(int);
int bitMask(int, int);
int test_bitMask(int, int);
int bitNor(int, int);
int test_bitNor(int, int);
int byteSwap(int, int, int);
int test_byteSwap(int, int, int);
int conditional(int, int, int);
int test_conditional(int, int, int);
int evenBits();
int test_evenBits();
int ezThreeFourths(int);
int test_ezThreeFourths(int);
int fitsShort(int);
int test_fitsShort(int);
int getByte(int, int);
int test_getByte(int, int);
int howManyBits(int);
int test_howManyBits(int);
int implication(int, int);
int test_implication(int, int);
int isAsciiDigit(int);
int test_isAsciiDigit(int);
int isGreater(int, int);
int test_isGreater(int, int);
int isNonNegative(int);
int test_isNonNegative(int);
int isTmax(int);
int test_isTmax(int);
int minusOne();
int test_minusOne();
int rotateRight(int, int);
int test_rotateRight(int, int);
int satAdd(int, int);
int test_satAdd(int, int);
int sign(int);
int test_sign(int);
int subOK(int, int);
int test_subOK(int, int);
